### ISSUE TITLE
Greetings!

### ISSUE THREAD

**Issue by ClickerMonkey** [anim8js/Janimate#1]
I don't know where the best place to put this is, this should suffice I think!

I'm the author of the "anim8js" library and its associated libraries:

- https://github.com/ClickerMonkey/anim8js
- https://github.com/ClickerMonkey/anim8js-dom
- https://github.com/ClickerMonkey/anim8js-jquery
- https://github.com/ClickerMonkey/anim8js-animate.css
- https://github.com/ClickerMonkey/anim8js-pixi
- https://github.com/ClickerMonkey/anim8js-easel

It seems you grabbed up this organization before I could! I've worked on this library almost 2 years now and I am interested in using your organization. 

It seems like by some crazy chance you actually started this library and are headed down the path I started almost 2 years ago.

If possible - I would greatly appreciate this organization if you don't have any other plans with it!

Thank You,

Philip Diffenderfer

**Comment by XtremePlayzCODE** [comment]
Hello, Philip.

Thank you for the information. I have forgotten all about this but have a complete version. I could put you as an owner, but I still want to put this library on GitHub, but on this organization. Since you have already completed yours, I can come up with a new repo name, but yes, you may have this organization.

Please respond with new project names for me if you have any!

XtremePlayzCODE

**Comment by ClickerMonkey** [comment]
Awesome!

Janimate sounds pretty good. Some others I can think of (and don't appear to be taken or related to animation):

- keyframejs
- inoutjs (in = intro, out = outro... tried to work em in there for emphasis)
- tranmationjs (transition + animation)
- excitejs
- energizejs

**Comment by XtremePlayzCODE** [comment]
Wow, you have amazing ideas! You can clone anim8js to this organization if you have not yet, I haven't checked.

XtremePlayzCODE

**Comment by ClickerMonkey** [comment]
Thanks!

I transfered it over and added an icon & logo - let me know what you think!

**Comment by XtremePlayzCODE** [comment]
Looks amazing! And I have renamed Janimate to KeyframeJS. Thanks for the idea!

XtremePlayzCODE
